# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, inputs, pkgs, modulesPath, ... }:

{
  imports =
    [
      inputs.nixos-hardware.nixosModules.framework-amd-ai-300-series
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enabling UKI. systemd >= 257 forces using UKI for TPM2 unseal.
  boot.bootspec.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;
  boot.initrd.systemd.enable = true;

  boot.initrd.availableKernelModules = [
    "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"
    "tpm" "tpm_tis" "tpm_crb" #this is needed for TPM2 support
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b9b0a1c1-6ec7-4cc8-9a9c-ecbddfe9ed24";
      fsType = "ext4";
    };

    boot.initrd.luks.devices."luks-07d49276-20f8-4162-b8fc-5c56099fe59a" = { 
      device = "/dev/disk/by-uuid/07d49276-20f8-4162-b8fc-5c56099fe59a"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F8A-93D5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp195s0f3u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Updating firmware using https://github.com/NixOS/nixos-hardware/
  services.fwupd.enable = true;

}
