# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # Enabling UKI. systemd >= 257 forces using UKI for TPM2 unseal.
  boot.bootspec.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;
  boot.initrd.systemd.enable = true;


  boot.initrd.availableKernelModules = [ 
    "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" 
    "tpm" "tpm_tis" "tpm_crb" #this is needed for TPM2 support
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.supportedFilesystems = [ "btrfs" ];
  boot.initrd.supportedFilesystems = [ "btrfs" ];

  boot.initrd.luks.devices = {
    "luks-nvme0n1p3" = { 
      device = "/dev/disk/by-uuid/9fd6099b-2f7f-4dd2-890f-695cbe6bc09d"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-nvme1n1p3" = { 
      device = "/dev/disk/by-uuid/87673dc9-edbe-4dbc-943d-188e6a4ca102"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-nvme0n1p2" = { 
      device = "/dev/disk/by-uuid/71bc26fe-e0ef-475a-b6fb-5dce6cd97f75"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-nvme1n1p2" = { 
      device = "/dev/disk/by-uuid/9efac2c0-dd11-4d64-b1ef-391d42127bc9"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-sda" = { 
      device = "/dev/disk/by-uuid/1f1b8282-68fc-45a6-aa95-a87f48a6a16e"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-sdb" = { 
      device = "/dev/disk/by-uuid/69d7cfef-0e25-4fbf-98e1-a1a98f3f54dd"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-sdc" = { 
      device = "/dev/disk/by-uuid/b817e731-ddda-44ae-a3e2-23a1d22ae40c"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };
    "luks-sdd" = { 
      device = "/dev/disk/by-uuid/da95eba7-4bbe-46f6-9fd6-b7e0ecd6922d"; 
      crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=0" ]; # As no secure boot, we only need PCR 0
    };

  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1457fd70-cea1-45a2-88d7-8e9e9fadde8c";
    fsType = "btrfs";
    options = [ "subvol=@nix-root" "compress=zstd:3" "ssd"  "noatime" "space_cache=v2" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1457fd70-cea1-45a2-88d7-8e9e9fadde8c";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd:3" "ssd"  "noatime" "space_cache=v2" ];
    neededForBoot = true;
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/1457fd70-cea1-45a2-88d7-8e9e9fadde8c";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" "compress=zstd:3" "ssd"  "noatime" "space_cache=v2" ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/5109-FD06";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-nvme0n1p2"; priority = 100; }
    { device = "/dev/mapper/luks-nvme1n1p2"; priority = 100; }
  ];

  ###
  # /home mount points

  fileSystems."/home/clvx/Documents" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-documents" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };
  fileSystems."/home/clvx/Downloads" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-downloads" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  fileSystems."/home/clvx/Code" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-code" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  fileSystems."/home/clvx/Music" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-music" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  fileSystems."/home/clvx/Pictures" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-pictures" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  fileSystems."/home/clvx/Templates" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-templates" "compress=zstd:3" "ssd"  "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  fileSystems."/home/clvx/Videos" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@users-clvx-videos" "compress=zstd:3" "ssd" "noatime"
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  # /srv/data mount points
  fileSystems."/srv/data/nextcloud" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@srv-data-nextcloud" "compress=zstd:3" "ssd" "discard=async" "noatime" 
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  # /srv/data mount points
  fileSystems."/srv/data/docker" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@srv-data-docker" "compress=zstd:3" "ssd" "discard=async" "noatime" 
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };

  # /srv/data mount points
  fileSystems."/srv/data/kubernetes" = {
    device = "/dev/mapper/luks-sda";
    fsType = "btrfs";
    options = [ "subvol=@srv-data-kubernetes" "compress=zstd:3" "ssd" "discard=async" "noatime" 
	"x-systemd.automount"   # lazy mount on first access
    	"nofail"                # don’t drop into rescue mode
    	"x-systemd.device-timeout=5s" ];
  };
  ###

  boot.resumeDevice = "/dev/mapper/luks-nvme0n1p2";
  boot.kernelParams = [ "resume=/dev/mapper/luks-nvme0n1p2" ];

  services.btrfs.autoScrub.enable = true;
  services.fstrim.enable = true;

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
